version: "3"

services:
  backend:
    build: .docker
    ports:
      - "127.0.0.1:${PORT}:4000"
    volumes:
      - ./:/app
    env_file:
      - .env
      - .env.local
  db:
    image: postgres:13.1
    ports:
      - "127.0.0.1:${DB_PORT}:5432"
    environment:
      - 'POSTGRES_USER=${DB_USERNAME}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_DB=${DB_DATABASE}'
